---
- name: Recompile naturebank
  command: >
    /usr/bin/python -OO -m compileall -x '^/opt/naturebank/venv/' /opt/naturebank /etc/opt/naturebank
  notify:
    - Migrate naturebank
    - Restart naturebank

- name: Migrate naturebank
  shell: >
    export PYTHONPATH=/etc/opt/naturebank:/opt/naturebank &&
    export DJANGO_SETTINGS_MODULE=settings &&
    ./venv/bin/python manage.py migrate
  args:
    chdir: /opt/naturebank

- name: Collect naturebank static files
  shell: >
    export PYTHONPATH=/etc/opt/naturebank:/opt/naturebank &&
    export DJANGO_SETTINGS_MODULE=settings &&
    ./venv/bin/python manage.py collectstatic --noinput
  args:
    chdir: /opt/naturebank

- name: Restart naturebank
  systemd:
    state: restarted
    name: naturebank
